[opener]
open = [
	{ run = 'xdg-open "$@"', orphan = true, desc = "Open", for = "linux" },
]
edit = [
	{ run = '${EDITOR:-vi} "$@"', block = true, desc = "Edit" },
]

[open]
rules = [
	{ url = "*/", use = [ "edit", "open", "reveal" ] },
	{ mime = "text/*", use = [ "open", "edit", "reveal" ] },
	{ mime = "image/*", use = [ "open", "reveal" ] },
	{ mime = "{audio,video}/*", use = [ "open", "reveal" ] },
	{ mime = "application/pdf", use = [ "open", "reveal" ] },
	{ mime = "application/{json,ndjson}", use = [ "open", "edit", "reveal" ] },
	{ mime = "*/javascript", use = [ "open", "edit", "reveal" ] },
	{ mime = "inode/empty", use = [ "edit", "reveal" ] },
	{ url = "*", use = [ "open", "reveal" ] },
]
