[opener]
vscode = [
	{ run = 'code "$@"', orphan = true, desc = "VSCode" },
]
vim = [
	{ run = 'vim "$@"', block = true, desc = "Vim" },
]
imv = [
	{ run = 'imv "$@"', orphan = true, desc = "imv" },
]
vlc = [
	{ run = 'vlc "$@"', orphan = true, desc = "VLC" },
]
firefox = [
	{ run = 'firefox "$@"', orphan = true, desc = "Firefox" },
]

[open]
rules = [
	{ url = "*/", use = [ "edit", "open" ] },
	{ mime = "text/*", use = [ "vim", "vscode" ] },
	{ mime = "image/*", use = [ "imv" ] },
	{ mime = "{audio,video}/*", use = [ "vlc" ] },
	{ mime = "application/pdf", use = [ "firefox" ] },
	{ mime = "application/{json,ndjson}", use = [ "vim", "vscode" ] },
	{ mime = "*/javascript", use = [ "vim", "vscode" ] },
	{ mime = "inode/empty", use = [ "vim", "vscode" ] },
	{ url = "*", use = [ "vim", "vscode" ] },
]
